cloud:
  aws:
    credentials:
      access-key: "Your Access Key"
      secret-key: "Ypur Secret Key"
    region:
      static: "region Name"
    stack:
      auto: false

application:
  bucket:
    name: s3filehub


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 2000MB
      max-request-size: 10MB

server:
  port: 8080

